# Generated by Django 5.2.10 on 2026-04-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=255, verbose_name='Mật khẩu (hashed)')),
                ('fullname', models.CharField(max_length=255, verbose_name='Họ tên đầy đủ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('role', models.CharField(choices=[('customer', 'Khách hàng'), ('manager', 'Quản lý nhà thuốc'), ('staff', 'Nhân viên (sản phẩm)'), ('admin', 'Quản trị viên')], default='customer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản người dùng',
                'ordering': ['-created_at'],
            },
        ),
    ]
